{
 "title": "EPOLCA UPDATES",
 "description": "Show ePolca Updates",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ePolca Versions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "https://mafesa-epolca.innovait.cat/api/monitor/factory/status",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Grafopack Updates",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "`some-epolca`",
     "rawSql": "SELECT  \nf.name as factory,\nu.type,\nu.error_sync,\nu.synced_at,\nu.time_spent\n FROM `grafopack-epolca`.updates u join `grafopack-epolca`.factories f on f.id = u.factory_id\n"
    }
   ]
  },
  {
   "title": "INOXTOP UPDATES",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "epolca",
     "rawSql": "SELECT  \nf.name as factory,\nu.type,\nu.error_sync,\nu.synced_at,\nu.time_spent\n FROM `epolca`.updates u join `epolca`.factories f on f.id = u.factory_id\n"
    }
   ]
  },
  {
   "title": "SOME Updates",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "`some-epolca`",
     "rawSql": "SELECT  \nf.name as factory,\nu.type,\nu.error_sync,\nu.synced_at,\nu.time_spent\n FROM `some-epolca`.updates u join `some-epolca`.factories f on f.id = u.factory_id\n"
    }
   ]
  }
 ]
}